### ISSUE TITLE
When will you start the work for the new version? 

### ISSUE THREAD

**Issue by dsijdshaij** [l1ttleO/PrismLauncher-elyby#29] opened 2024-11-22 20:12 UTC
### Role

Ely Prism 

### Suggestion

Update to fix ely by skin system

### Benefit

So thats the whole point of the launcher, even the title - ELYPrismLauncher says it. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Please, update launcher, we need this very much. 
When will you start to work with the update?

**Comment by mctaylors** [comment] 2024-11-22 20:24
> ### This suggestion is unique
> 
>  * [x]  I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

i swear to god #26

**Comment by dsijdshaij** [comment] 2024-11-22 20:57
> > ### This suggestion is unique
> > 
> > * [x]   I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.
> 
> i swear to god #26

Difficult doesnt supposed to mean that you need to sleep for months

**Comment by mctaylors** [comment] 2024-11-22 22:02
> > > ### This suggestion is unique
> > > 
> > > * [x]    I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.
> > 
> > 
> > i swear to god #26
> 
> Difficult doesnt supposed to mean that you need to sleep for months

first of all: current version of EPL works. i tested it by myself literally 1 hour ago. there is nothing to fix in this version.
and did you know that the maintainer also has other projects to work with?
ElyPrismLauncher won't be updated unless Ely.by devs add necessary API.
if you're not comfortable with that, then go ahead, make a PR that won't break anything.

**Comment by dsijdshaij** [comment] 2024-11-23 06:27
> > > > ### This suggestion is unique
> > > > 
> > > > * [x]     I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.
> > > 
> > > 
> > > i swear to god #26
> > 
> > 
> > Difficult doesnt supposed to mean that you need to sleep for months
> 
> first of all: current version of EPL works. i tested it by myself literally 1 hour ago. there is nothing to fix in this version. and did you know that the maintainer also has other projects to work with? ElyPrismLauncher won't be updated unless Ely.by devs add necessary API. if you're not comfortable with that, then go ahead, make a PR that won't break anything.

Ok mine just dont work

**Comment by Octol1ttle** [comment] 2024-11-23 09:11
Duplicate of #26. I don't owe anyone anything and can "sleep" for as long as I want or need.

**Closed as not planned by Octol1ttle** 2024-11-23 09:11 UTC
Labels: enhancement
